package com.sherwinca.entidades;
// Generated 06-01-2015 11:32:31 PM by Hibernate Tools 3.6.0



/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private int idalumno;
     private String nombres;
     private String aplellidos;

    public Alumnos() {
    }

    public Alumnos(String nombres, String aplellidos) {
       this.nombres = nombres;
       this.aplellidos = aplellidos;
    }
   
    public int getIdalumno() {
        return this.idalumno;
    }
    
    public void setIdalumno(int idalumno) {
        this.idalumno = idalumno;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getAplellidos() {
        return this.aplellidos;
    }
    
    public void setAplellidos(String aplellidos) {
        this.aplellidos = aplellidos;
    }




}


