package com.sherwinca.entidades;
// Generated 06-01-2015 11:32:31 PM by Hibernate Tools 3.6.0



/**
 * SigAltasbajas generated by hbm2java
 */
public class SigAltasbajas  implements java.io.Serializable {


     private int SPkAb;
     private String vcNmbempAb;
     private String vcApAb;
     private int IEstadoAb;
     private String vcMesAb;
     private String vcAreaAb;
private Integer iAnioAb;
    public SigAltasbajas() {
    }

    public SigAltasbajas(int SPkAb, String vcNmbempAb, String vcApAb, int IEstadoAb, String vcMesAb, String vcAreaAb, Integer iAnioAb) {
       this.SPkAb = SPkAb;
       this.vcNmbempAb = vcNmbempAb;
       this.vcApAb = vcApAb;
       this.IEstadoAb = IEstadoAb;
       this.vcMesAb = vcMesAb;
       this.vcAreaAb = vcAreaAb;
       this.iAnioAb = iAnioAb;
    }
   
    public int getSPkAb() {
        return this.SPkAb;
    }
    
    public void setSPkAb(int SPkAb) {
        this.SPkAb = SPkAb;
    }
    public String getVcNmbempAb() {
        return this.vcNmbempAb;
    }
    
    public void setVcNmbempAb(String vcNmbempAb) {
        this.vcNmbempAb = vcNmbempAb;
    }
    public String getVcApAb() {
        return this.vcApAb;
    }
    
    public void setVcApAb(String vcApAb) {
        this.vcApAb = vcApAb;
    }
    public int getIEstadoAb() {
        return this.IEstadoAb;
    }
    
    public void setIEstadoAb(int IEstadoAb) {
        this.IEstadoAb = IEstadoAb;
    }
    public String getVcMesAb() {
        return this.vcMesAb;
    }
    
    public void setVcMesAb(String vcMesAb) {
        this.vcMesAb = vcMesAb;
    }
    public String getVcAreaAb() {
        return this.vcAreaAb;
    }
    
    public void setVcAreaAb(String vcAreaAb) {
        this.vcAreaAb = vcAreaAb;
    }

    /**
     * @return the iAnioAb
     */
    public Integer getiAnioAb() {
        return iAnioAb;
    }

    /**
     * @param iAnioAb the iAnioAb to set
     */
    public void setiAnioAb(Integer iAnioAb) {
        this.iAnioAb = iAnioAb;
    }




}


