package com.sherwinca.entidades;
// Generated 06-01-2015 11:32:31 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * SigCapacitacionimpartida generated by hbm2java
 */
public class SigCapacitacionimpartida  implements java.io.Serializable {


     private int SPkCapacitacion;
     private String vcNmbempCapacitacion;
     private String vcApCapacitacion;
     private String vcNmbcursoCapacitacion;
     private String vcNmbuniCapacitacion;
     private int IDiasCapacitacion;
     private BigDecimal DCostoCapacitacion;
     private int IFaltasCapacitacion;

    public SigCapacitacionimpartida() {
    }

    public SigCapacitacionimpartida(int SPkCapacitacion, String vcNmbempCapacitacion, String vcApCapacitacion, String vcNmbcursoCapacitacion, String vcNmbuniCapacitacion, int IDiasCapacitacion, BigDecimal DCostoCapacitacion, int IFaltasCapacitacion) {
       this.SPkCapacitacion = SPkCapacitacion;
       this.vcNmbempCapacitacion = vcNmbempCapacitacion;
       this.vcApCapacitacion = vcApCapacitacion;
       this.vcNmbcursoCapacitacion = vcNmbcursoCapacitacion;
       this.vcNmbuniCapacitacion = vcNmbuniCapacitacion;
       this.IDiasCapacitacion = IDiasCapacitacion;
       this.DCostoCapacitacion = DCostoCapacitacion;
       this.IFaltasCapacitacion = IFaltasCapacitacion;
    }
   
    public int getSPkCapacitacion() {
        return this.SPkCapacitacion;
    }
    
    public void setSPkCapacitacion(int SPkCapacitacion) {
        this.SPkCapacitacion = SPkCapacitacion;
    }
    public String getVcNmbempCapacitacion() {
        return this.vcNmbempCapacitacion;
    }
    
    public void setVcNmbempCapacitacion(String vcNmbempCapacitacion) {
        this.vcNmbempCapacitacion = vcNmbempCapacitacion;
    }
    public String getVcApCapacitacion() {
        return this.vcApCapacitacion;
    }
    
    public void setVcApCapacitacion(String vcApCapacitacion) {
        this.vcApCapacitacion = vcApCapacitacion;
    }
    public String getVcNmbcursoCapacitacion() {
        return this.vcNmbcursoCapacitacion;
    }
    
    public void setVcNmbcursoCapacitacion(String vcNmbcursoCapacitacion) {
        this.vcNmbcursoCapacitacion = vcNmbcursoCapacitacion;
    }
    public String getVcNmbuniCapacitacion() {
        return this.vcNmbuniCapacitacion;
    }
    
    public void setVcNmbuniCapacitacion(String vcNmbuniCapacitacion) {
        this.vcNmbuniCapacitacion = vcNmbuniCapacitacion;
    }
    public int getIDiasCapacitacion() {
        return this.IDiasCapacitacion;
    }
    
    public void setIDiasCapacitacion(int IDiasCapacitacion) {
        this.IDiasCapacitacion = IDiasCapacitacion;
    }
    public BigDecimal getDCostoCapacitacion() {
        return this.DCostoCapacitacion;
    }
    
    public void setDCostoCapacitacion(BigDecimal DCostoCapacitacion) {
        this.DCostoCapacitacion = DCostoCapacitacion;
    }
    public int getIFaltasCapacitacion() {
        return this.IFaltasCapacitacion;
    }
    
    public void setIFaltasCapacitacion(int IFaltasCapacitacion) {
        this.IFaltasCapacitacion = IFaltasCapacitacion;
    }




}


