package com.sherwinca.entidades;
// Generated 06-01-2015 11:32:31 PM by Hibernate Tools 3.6.0



/**
 * SigFaltasgraves generated by hbm2java
 */
public class SigFaltasgraves  implements java.io.Serializable {


     private int SPkFaltas;
     private String vcNmbempFaltas;
     private String vcApFaltas;
     private String vcMesFaltas;
     private String vcAreaFaltas;
     private int INoFallas;
     private Integer iAnioFaltas;

    public SigFaltasgraves() {
    }

    public SigFaltasgraves(int SPkFaltas, String vcNmbempFaltas, String vcApFaltas, String vcMesFaltas, String vcAreaFaltas, int INoFallas, Integer iAnioFaltas) {
       this.SPkFaltas = SPkFaltas;
       this.vcNmbempFaltas = vcNmbempFaltas;
       this.vcApFaltas = vcApFaltas;
       this.vcMesFaltas = vcMesFaltas;
       this.vcAreaFaltas = vcAreaFaltas;
       this.INoFallas = INoFallas;
       this.iAnioFaltas = iAnioFaltas;
    }
   
    public int getSPkFaltas() {
        return this.SPkFaltas;
    }
    
    public void setSPkFaltas(int SPkFaltas) {
        this.SPkFaltas = SPkFaltas;
    }
    public String getVcNmbempFaltas() {
        return this.vcNmbempFaltas;
    }
    
    public void setVcNmbempFaltas(String vcNmbempFaltas) {
        this.vcNmbempFaltas = vcNmbempFaltas;
    }
    public String getVcApFaltas() {
        return this.vcApFaltas;
    }
    
    public void setVcApFaltas(String vcApFaltas) {
        this.vcApFaltas = vcApFaltas;
    }
    public String getVcMesFaltas() {
        return this.vcMesFaltas;
    }
    
    public void setVcMesFaltas(String vcMesFaltas) {
        this.vcMesFaltas = vcMesFaltas;
    }
    public String getVcAreaFaltas() {
        return this.vcAreaFaltas;
    }
    
    public void setVcAreaFaltas(String vcAreaFaltas) {
        this.vcAreaFaltas = vcAreaFaltas;
    }
    public int getINoFallas() {
        return this.INoFallas;
    }
    
    public void setINoFallas(int INoFallas) {
        this.INoFallas = INoFallas;
    }

    public Integer getiAnioFaltas() {
        return iAnioFaltas;
    }

    public void setiAnioFaltas(Integer iAnioFaltas) {
        this.iAnioFaltas = iAnioFaltas;
    }




}


