package com.sherwinca.entidades;
// Generated 06-01-2015 11:32:31 PM by Hibernate Tools 3.6.0



/**
 * SigGastoausentismo generated by hbm2java
 */
public class SigGastoausentismo  implements java.io.Serializable {


     private int SPkAusentismo;
     private String vcNmbempAusentismo;
     private String vcApAusentismo;
     private int IHorasAusentismo;
     private String vcAreaAusentismo;
     private int ITipopermisoAusentismo;
     private String vcMesAusentismo;
     private int iAnioAusentismo;

    public SigGastoausentismo() {
    }

    public SigGastoausentismo(int SPkAusentismo, String vcNmbempAusentismo, 
            String vcApAusentismo, int IHorasAusentismo, String vcAreaAusentismo,
            int ITipopermisoAusentismo, String vcMesAusentismo, int iAnioAusentismo) {
       this.SPkAusentismo = SPkAusentismo;
       this.vcNmbempAusentismo = vcNmbempAusentismo;
       this.vcApAusentismo = vcApAusentismo;
       this.IHorasAusentismo = IHorasAusentismo;
       this.vcAreaAusentismo = vcAreaAusentismo;
       this.ITipopermisoAusentismo = ITipopermisoAusentismo;
       this.vcMesAusentismo = vcMesAusentismo;
       this.iAnioAusentismo = iAnioAusentismo;
    }
   
    public int getSPkAusentismo() {
        return this.SPkAusentismo;
    }
    
    public void setSPkAusentismo(int SPkAusentismo) {
        this.SPkAusentismo = SPkAusentismo;
    }
    public String getVcNmbempAusentismo() {
        return this.vcNmbempAusentismo;
    }
    
    public void setVcNmbempAusentismo(String vcNmbempAusentismo) {
        this.vcNmbempAusentismo = vcNmbempAusentismo;
    }
    public String getVcApAusentismo() {
        return this.vcApAusentismo;
    }
    
    public void setVcApAusentismo(String vcApAusentismo) {
        this.vcApAusentismo = vcApAusentismo;
    }
    public int getIHorasAusentismo() {
        return this.IHorasAusentismo;
    }
    
    public void setIHorasAusentismo(int IHorasAusentismo) {
        this.IHorasAusentismo = IHorasAusentismo;
    }
    public String getVcAreaAusentismo() {
        return this.vcAreaAusentismo;
    }
    
    public void setVcAreaAusentismo(String vcAreaAusentismo) {
        this.vcAreaAusentismo = vcAreaAusentismo;
    }
    public int getITipopermisoAusentismo() {
        return this.ITipopermisoAusentismo;
    }
    
    public void setITipopermisoAusentismo(int ITipopermisoAusentismo) {
        this.ITipopermisoAusentismo = ITipopermisoAusentismo;
    }
    public String getVcMesAusentismo() {
        return this.vcMesAusentismo;
    }
    
    public void setVcMesAusentismo(String vcMesAusentismo) {
        this.vcMesAusentismo = vcMesAusentismo;
    }

    public int getiAnioAusentismo() {
        return iAnioAusentismo;
    }

    public void setiAnioAusentismo(int iAnioAusentismo) {
        this.iAnioAusentismo = iAnioAusentismo;
    }

   


}


