package com.sherwinca.entidades;
// Generated 06-01-2015 11:32:31 PM by Hibernate Tools 3.6.0



/**
 * SigLimitepermiso generated by hbm2java
 */
public class SigLimitepermiso  implements java.io.Serializable {


     private int SPkLimite;
     private String vcNmbempLimite;
     private String vcApLimite;
     private String vcAreaLimite;
     private Integer INopermisoLimite;

    public SigLimitepermiso() {
    }

	
    public SigLimitepermiso(int SPkLimite, String vcNmbempLimite, String vcApLimite, String vcAreaLimite) {
        this.SPkLimite = SPkLimite;
        this.vcNmbempLimite = vcNmbempLimite;
        this.vcApLimite = vcApLimite;
        this.vcAreaLimite = vcAreaLimite;
    }
    public SigLimitepermiso(int SPkLimite, String vcNmbempLimite, String vcApLimite, String vcAreaLimite, Integer INopermisoLimite) {
       this.SPkLimite = SPkLimite;
       this.vcNmbempLimite = vcNmbempLimite;
       this.vcApLimite = vcApLimite;
       this.vcAreaLimite = vcAreaLimite;
       this.INopermisoLimite = INopermisoLimite;
    }
   
    public int getSPkLimite() {
        return this.SPkLimite;
    }
    
    public void setSPkLimite(int SPkLimite) {
        this.SPkLimite = SPkLimite;
    }
    public String getVcNmbempLimite() {
        return this.vcNmbempLimite;
    }
    
    public void setVcNmbempLimite(String vcNmbempLimite) {
        this.vcNmbempLimite = vcNmbempLimite;
    }
    public String getVcApLimite() {
        return this.vcApLimite;
    }
    
    public void setVcApLimite(String vcApLimite) {
        this.vcApLimite = vcApLimite;
    }
    public String getVcAreaLimite() {
        return this.vcAreaLimite;
    }
    
    public void setVcAreaLimite(String vcAreaLimite) {
        this.vcAreaLimite = vcAreaLimite;
    }
    public Integer getINopermisoLimite() {
        return this.INopermisoLimite;
    }
    
    public void setINopermisoLimite(Integer INopermisoLimite) {
        this.INopermisoLimite = INopermisoLimite;
    }




}


