package com.sherwinca.entidades;
// Generated 06-01-2015 11:32:31 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * SigModulo generated by hbm2java
 */
public class SigModulo  implements java.io.Serializable {


     private int SPkModulo;
     private String vcNmbModulo;
     private String vcUrlModulo;
     private String vcDescripcionModulo;
     private Set sigPerfileses = new HashSet(0);

    public SigModulo() {
    }

	
    public SigModulo(int SPkModulo, String vcNmbModulo, String vcUrlModulo) {
        this.SPkModulo = SPkModulo;
        this.vcNmbModulo = vcNmbModulo;
        this.vcUrlModulo = vcUrlModulo;
    }
    public SigModulo(int SPkModulo, String vcNmbModulo, String vcUrlModulo, String vcDescripcionModulo, Set sigPerfileses) {
       this.SPkModulo = SPkModulo;
       this.vcNmbModulo = vcNmbModulo;
       this.vcUrlModulo = vcUrlModulo;
       this.vcDescripcionModulo = vcDescripcionModulo;
       this.sigPerfileses = sigPerfileses;
    }
   
    public int getSPkModulo() {
        return this.SPkModulo;
    }
    
    public void setSPkModulo(int SPkModulo) {
        this.SPkModulo = SPkModulo;
    }
    public String getVcNmbModulo() {
        return this.vcNmbModulo;
    }
    
    public void setVcNmbModulo(String vcNmbModulo) {
        this.vcNmbModulo = vcNmbModulo;
    }
    public String getVcUrlModulo() {
        return this.vcUrlModulo;
    }
    
    public void setVcUrlModulo(String vcUrlModulo) {
        this.vcUrlModulo = vcUrlModulo;
    }
    public String getVcDescripcionModulo() {
        return this.vcDescripcionModulo;
    }
    
    public void setVcDescripcionModulo(String vcDescripcionModulo) {
        this.vcDescripcionModulo = vcDescripcionModulo;
    }
    public Set getSigPerfileses() {
        return this.sigPerfileses;
    }
    
    public void setSigPerfileses(Set sigPerfileses) {
        this.sigPerfileses = sigPerfileses;
    }




}


