package com.sherwinca.entidades;
// Generated 06-01-2015 11:32:31 PM by Hibernate Tools 3.6.0



/**
 * SigPersonalcontratado generated by hbm2java
 */
public class SigPersonalcontratado  implements java.io.Serializable {


     private int SPkContratado;
     private String vcNmbempContratado;
     private String vcApContratado;
     private String vcAreaContratado;
     private int IAnioContratado;

    public SigPersonalcontratado() {
    }

    public SigPersonalcontratado(int SPkContratado, String vcNmbempContratado, String vcApContratado, String vcAreaContratado, int IAnioContratado) {
       this.SPkContratado = SPkContratado;
       this.vcNmbempContratado = vcNmbempContratado;
       this.vcApContratado = vcApContratado;
       this.vcAreaContratado = vcAreaContratado;
       this.IAnioContratado = IAnioContratado;
    }
   
    public int getSPkContratado() {
        return this.SPkContratado;
    }
    
    public void setSPkContratado(int SPkContratado) {
        this.SPkContratado = SPkContratado;
    }
    public String getVcNmbempContratado() {
        return this.vcNmbempContratado;
    }
    
    public void setVcNmbempContratado(String vcNmbempContratado) {
        this.vcNmbempContratado = vcNmbempContratado;
    }
    public String getVcApContratado() {
        return this.vcApContratado;
    }
    
    public void setVcApContratado(String vcApContratado) {
        this.vcApContratado = vcApContratado;
    }
    public String getVcAreaContratado() {
        return this.vcAreaContratado;
    }
    
    public void setVcAreaContratado(String vcAreaContratado) {
        this.vcAreaContratado = vcAreaContratado;
    }
    public int getIAnioContratado() {
        return this.IAnioContratado;
    }
    
    public void setIAnioContratado(int IAnioContratado) {
        this.IAnioContratado = IAnioContratado;
    }




}


