package com.sherwinca.entidades;
// Generated 06-01-2015 11:32:31 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * SigPersonaldisponible generated by hbm2java
 */
public class SigPersonaldisponible  implements java.io.Serializable {


     private int SPkDisponible;
     private String vcNmbempDisponible;
     private String vcApDisponible;
     private int iHoraDisponible;
     private String vcMesDisponible;
     private String vcAreaDisponible;
     private int iAnioDisponible;

    public SigPersonaldisponible() {
    }

    public SigPersonaldisponible(int SPkDisponible, String vcNmbempDisponible, String vcApDisponible, int iHoraDisponible, String vcMesDisponible, String vcAreaDisponible, int iAnioDisponible) {
       this.SPkDisponible = SPkDisponible;
       this.vcNmbempDisponible = vcNmbempDisponible;
       this.vcApDisponible = vcApDisponible;
       this.iHoraDisponible = iHoraDisponible;
       this.vcMesDisponible = vcMesDisponible;
       this.vcAreaDisponible = vcAreaDisponible;
       this.iAnioDisponible = iAnioDisponible;
    }
   
    public int getSPkDisponible() {
        return this.SPkDisponible;
    }
    
    public void setSPkDisponible(int SPkDisponible) {
        this.SPkDisponible = SPkDisponible;
    }
    public String getVcNmbempDisponible() {
        return this.vcNmbempDisponible;
    }
    
    public void setVcNmbempDisponible(String vcNmbempDisponible) {
        this.vcNmbempDisponible = vcNmbempDisponible;
    }
    public String getVcApDisponible() {
        return this.vcApDisponible;
    }
    
    public void setVcApDisponible(String vcApDisponible) {
        this.vcApDisponible = vcApDisponible;
    }
    public int getiHoraDisponible() {
        return this.iHoraDisponible;
    }
    
    public void setiHoraDisponible(int iHoraDisponible) {
        this.iHoraDisponible = iHoraDisponible;
    }
    public String getVcMesDisponible() {
        return this.vcMesDisponible;
    }
    
    public void setVcMesDisponible(String vcMesDisponible) {
        this.vcMesDisponible = vcMesDisponible;
    }
    public String getVcAreaDisponible() {
        return this.vcAreaDisponible;
    }
    
    public void setVcAreaDisponible(String vcAreaDisponible) {
        this.vcAreaDisponible = vcAreaDisponible;
    }
    public int getiAnioDisponible(){
        return this.iAnioDisponible;
    }
    public void setiAnioDisponible(int iAnioDisponible){
        this.iAnioDisponible = iAnioDisponible;
    }



}


