package com.sherwinca.entidades;
// Generated 06-01-2015 11:32:31 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * SigRotacionrrhh generated by hbm2java
 */
public class SigRotacionrrhh  implements java.io.Serializable {


     private int SPkRotrrhh;
     private String vcNmbRotrrhh;
     private String vcApRotrrhh;
     private int ITiporotRotrrhh;
     private String vcAreaRotrrhh;
     private Date dtRotRotrrhh;

    public SigRotacionrrhh() {
    }

    public SigRotacionrrhh(int SPkRotrrhh, String vcNmbRotrrhh, String vcApRotrrhh, int ITiporotRotrrhh, String vcAreaRotrrhh, Date dtRotRotrrhh) {
       this.SPkRotrrhh = SPkRotrrhh;
       this.vcNmbRotrrhh = vcNmbRotrrhh;
       this.vcApRotrrhh = vcApRotrrhh;
       this.ITiporotRotrrhh = ITiporotRotrrhh;
       this.vcAreaRotrrhh = vcAreaRotrrhh;
       this.dtRotRotrrhh = dtRotRotrrhh;
    }
   
    public int getSPkRotrrhh() {
        return this.SPkRotrrhh;
    }
    
    public void setSPkRotrrhh(int SPkRotrrhh) {
        this.SPkRotrrhh = SPkRotrrhh;
    }
    public String getVcNmbRotrrhh() {
        return this.vcNmbRotrrhh;
    }
    
    public void setVcNmbRotrrhh(String vcNmbRotrrhh) {
        this.vcNmbRotrrhh = vcNmbRotrrhh;
    }
    public String getVcApRotrrhh() {
        return this.vcApRotrrhh;
    }
    
    public void setVcApRotrrhh(String vcApRotrrhh) {
        this.vcApRotrrhh = vcApRotrrhh;
    }
    public int getITiporotRotrrhh() {
        return this.ITiporotRotrrhh;
    }
    
    public void setITiporotRotrrhh(int ITiporotRotrrhh) {
        this.ITiporotRotrrhh = ITiporotRotrrhh;
    }
    public String getVcAreaRotrrhh() {
        return this.vcAreaRotrrhh;
    }
    
    public void setVcAreaRotrrhh(String vcAreaRotrrhh) {
        this.vcAreaRotrrhh = vcAreaRotrrhh;
    }
    public Date getDtRotRotrrhh() {
        return this.dtRotRotrrhh;
    }
    
    public void setDtRotRotrrhh(Date dtRotRotrrhh) {
        this.dtRotRotrrhh = dtRotRotrrhh;
    }




}


