package com.sherwinca.entidades;
// Generated 06-01-2015 11:32:31 PM by Hibernate Tools 3.6.0



/**
 * SigUsuario generated by hbm2java
 */
public class SigUsuario  implements java.io.Serializable {


     private int SPkUsuario;
     private SigPerfiles sigPerfiles;
     private String vcNmbUsuario;
     private String vcPasswordUsuario;

    public SigUsuario() {
    }

    public SigUsuario(int SPkUsuario, SigPerfiles sigPerfiles, String vcNmbUsuario, String vcPasswordUsuario) {
       this.SPkUsuario = SPkUsuario;
       this.sigPerfiles = sigPerfiles;
       this.vcNmbUsuario = vcNmbUsuario;
       this.vcPasswordUsuario = vcPasswordUsuario;
    }
   
    public int getSPkUsuario() {
        return this.SPkUsuario;
    }
    
    public void setSPkUsuario(int SPkUsuario) {
        this.SPkUsuario = SPkUsuario;
    }
    public SigPerfiles getSigPerfiles() {
        return this.sigPerfiles;
    }
    
    public void setSigPerfiles(SigPerfiles sigPerfiles) {
        this.sigPerfiles = sigPerfiles;
    }
    public String getVcNmbUsuario() {
        return this.vcNmbUsuario;
    }
    
    public void setVcNmbUsuario(String vcNmbUsuario) {
        this.vcNmbUsuario = vcNmbUsuario;
    }
    public String getVcPasswordUsuario() {
        return this.vcPasswordUsuario;
    }
    
    public void setVcPasswordUsuario(String vcPasswordUsuario) {
        this.vcPasswordUsuario = vcPasswordUsuario;
    }




}


